export enum ControlCalculatorSortEnum {
	percentIn = 'percentIn',
	percentOut = 'percentOut',
	bind = 'bind',
	stopTime = 'stopTime',
	stopPercent = 'stopPercent',
	profitPercent = 'profitPercent',
	averageProfitPercent = 'averageProfitPercent',
	total = 'total',
	totalStops = 'totalStops',
	totalTakes = 'totalTakes',
	coefficient = 'coefficient',
	ratio = 'ratio',
	winRate = 'winRate',
	maxTimeDeal = 'maxTimeDeal',
	averageTimeDeal = 'averageTimeDeal',
	maxDrawdown = 'maxDrawdown',
	averageDrawdown = 'averageDrawdown',
	drawdownProfitRatio = 'drawdownProfitRatio',
	score = 'score'
}